// ============================================================
// EL DECK como DATOS. Esto es lo que un editor estilo Canva
// produciria/editaria. Cada objeto = una slide del repertorio.
// ============================================================

export const DECK = [
  {
    type: 'cover',
    section: 'Apertura',
    label: 'Portada',
    module: 'Módulo 0:',
    title: 'NOM', titleAccent: '035',
    photo: 'assets/portada.jpg',
    cobrand: { hp: 'color', inst: 'white' },
  },
  {
    type: 'mission',
    kicker: 'Misión 1.',
    title: ['Lluvia de ideas:', '¿Qué sabes de la', 'NOM 035?'],
    cobrand: { hp: 'color', inst: 'azul' },
  },
  {
    type: 'content',
    kicker: '¿Cuáles serían?',
    title: ['Condiciones', 'favorables', 'para el', 'trabajo.'],
    cobrand: { hp: 'color', inst: 'azul' },
  },
  {
    type: 'content-r',
    kicker: '¿Cuáles serían?',
    title: [
      [{t: 'CONDICIONES '}, {t: 'DES', c: 'sky'}, {t: 'FAVORABLES'}],
      'PARA EL',
      'TRABAJO.',
    ],
    cobrand: { hp: 'color', inst: 'azul' },
  },
  {
    type: 'semaforo',
    label: 'Dinámica · El Semáforo',
  },
  {
    type: 'nom-intro',
    section: '¿Qué es la NOM-035?',
    lead: 'Identificación, análisis y prevención de factores de riesgo psicosocial en el trabajo.',
    title: 'NOM 035 STPS 2018',
    cobrand: { inst: 'azul' },
  },
  {
    type: 'nom-goal',
    title: ['PROMOVER', 'UN ENTORNO', 'LABORAL', 'SALUDABLE.'],
    objLabel: 'Objetivo',
    body: [
      { t: 'Establecer los elementos para identificar, analizar y prevenir ' },
      { t: 'factores de riesgo psicosocial', em: true },
      { t: ', así como promover un ' },
      { t: 'entorno laboral saludable', em: true },
      { t: ' en los centros de trabajo.' },
    ],
    cobrand: { inst: 'azul' },
  },
  {
    type: 'nom-what',
    title: 'NOM-035-STPS-2018',
    q: '¿Qué es?',
    text: [
      'Es una herramienta fundamental para garantizar',
      'la salud mental de los trabajadores y mejorar',
      'la calidad de vida en los centros de trabajo.',
      'Su implementación no solo es un requisito legal,',
      'sino también una inversión en el capital humano',
      'de las empresas.',
    ],
    cobrand: { inst: 'azul' },
  },
  {
    type: 'nom-what',
    title: 'NOM-035-STPS-2018',
    q: 'Contexto',
    text: [
      'Fue emitida por la Secretaría del Trabajo y',
      'Previsión Social (STPS) en México y entró en vigor',
      'el 23 de octubre de 2019.',
    ],
    cobrand: { inst: 'azul' },
  },
  {
    type: 'nom-what',
    title: 'NOM-035-STPS-2018',
    q: 'Propósito',
    text: [
      'Mejorar las condiciones laborales y promover la salud mental',
      'de los trabajadores.',
    ],
    cobrand: { inst: 'azul' },
  },
  {
    type: 'nom-question',
    title: ['¿QUIÉNES ESTÁN', 'OBLIGADOS A DAR', 'CUMPLIMIENTO A', 'LA NOM-035?'],
    cobrand: { inst: 'azul' },
  },
  {
    type: 'nom-quadrants',
    admin: 'ADMINISTRATIVOS',
    jefes: 'JEFES',
    todos: ['TODOS LOS', 'TRABAJADORES'],
    sind: 'SINDICALIZADOS',
  },
  {
    type: 'nom-question',
    title: ['TODOS LOS', 'TRABAJADORES'],
    cobrand: { inst: 'azul' },
  },
  {
    type: 'nom-sky-text',
    kicker: ['CAMPO DE', 'APLICACIÓN'],
    body: [
      { t: 'La presente Norma Oficial Mexicana rige en todo el territorio nacional, aplica a todos los centros de trabajo, así como a ' },
      { t: 'todos', em: true },
      { t: ' los colaboradores sin distinción alguna.' },
    ],
    cobrand: { inst: 'azul' },
  },
  {
    type: 'swipe',
  },
  {
    type: 'nom-wedge',
    section: 'Factores de riesgo psicosocial',
    title: ['¿QUÉ HAY EN COMÚN', 'CON SITUACIONES', 'IDENTIFICADAS COMO', 'CONDICIONES DE TRABAJO', 'DESFAVORABLES?'],
    cobrand: { inst: 'azul' },
  },
  {
    type: 'nom-title',
    title: [
      ['¿QUÉ SON LOS ', { t: 'FACTORES', c: 'paper' }],
      [{ t: 'DE RIESGO PSICOSOCIAL', c: 'paper' }],
      'EN EL TRABAJO?',
    ],
    cobrand: { inst: 'azul' },
  },
  {
    type: 'nom-para',
    body: [
      'Los factores de riesgo psicosocial son condiciones',
      'relacionadas con la organización, el contenido y la realización',
      'del trabajo. Cuando estas características superan la capacidad',
      'y resistencia del empleado.',
    ],
    cobrand: { inst: 'azul' },
  },
  {
    type: 'nom-factor',
    title: ['FACTOR 1: CONDICIONES EN EL', 'AMBIENTE DE TRABAJO.'],
    body: [
      'Factores físicos y sociales',
      'que pueden impactar',
      'negativamente en el',
      'bienestar del trabajador.',
    ],
    cobrand: { inst: 'azul' },
  },
  {
    type: 'nom-ask',
    title: ['¿CÓMO SE VE', 'ESTE FACTOR', 'EN EL TRABAJO', 'DIARIO?'],
    cobrand: { inst: 'azul' },
  },
  {
    type: 'nom-quad-cond',
    inseguras: ['CONDICIONES', 'INSEGURAS'],
    insalubres: ['CONDICIONES', 'INSALUBRES'],
    peligrosas: ['CONDICIONES', 'PELIGROSAS'],
    cobrand: { inst: 'azul' },
  },
  {
    type: 'nom-factor',
    title: ['FACTOR 2: CARGA DE', 'TRABAJO', 'EXCESIVA.'],
    body: [
      'Cantidad y complejidad de las',
      'tareas que un trabajador debe',
      'realizar en tiempo determinado',
      'y que exceden su capacidad',
      'para realizarlas.',
    ],
    cobrand: { inst: 'azul' },
  },
  {
    type: 'nom-ask',
    title: ['¿CUÁNDO SE', 'CONSIDERA', 'CARGA EXCESIVA DE', 'TRABAJO?'],
    cobrand: { inst: 'azul' },
  },
  {
    type: 'nom-quad-def',
    rebasa: { h: ['REBASA'], s: ['la capacidad física', 'o mental del trabajador.'] },
    noPermite: { h: ['NO PERMITE'], s: ['recuperación', 'adecuada.'] },
    genera: { h: ['GENERA', 'ESTRÉS'], s: ['errores o riesgos'] },
    cobrand: { inst: 'azul' },
  },
  {
    type: 'nom-factor',
    title: ['FACTOR 3: FALTA DE', 'CONTROL', 'SOBRE EL TRABAJO.'],
    body: [
      'Situaciones en las que el trabajador',
      'tiene poca o ninguna capacidad de',
      'influir en las decisiones',
      'relacionadas',
      'a su trabajo u organizar sus tareas.',
    ],
    cobrand: { inst: 'azul' },
  },
  {
    type: 'nom-ask',
    title: ['¿CÓMO SE VE', 'ESTE FACTOR', 'EN EL TRABAJO', 'DIARIO?'],
    cobrand: { inst: 'azul' },
  },
  {
    type: 'nom-quad-cond',
    inseguras: ['INSTRUCCIONES', 'CONTRADICTORIAS'],
    insalubres: ['CAMBIOS CONSTANTES', 'EN LA OPERACIÓN'],
    peligrosas: ['DESCONOCIMIENTO DE', 'RESPONSABILIDADES'],
    cobrand: { inst: 'azul' },
  },
  {
    type: 'nom-factor',
    title: ['FACTOR 4: LIDERAZGO', 'NEGATIVO.'],
    body: [
      'Liderazgo gestionado con actitud',
      'agresiva; falta de claridad de las',
      'funciones en las actividades,',
      'y escaso o nulo reconocimiento y',
      'retroalimentación del desempeño.',
    ],
    cobrand: { inst: 'azul' },
  },
  {
    type: 'nom-ask',
    title: ['UN SUPERVISOR', 'CON LIDERAZGO', 'NEGATIVO'],
    cobrand: { inst: 'azul' },
  },
  {
    type: 'nom-quad-cond',
    inseguras: ['PRESIONA', 'CONSTANTEMENTE'],
    insalubres: ['HUMILLA FRENTE', 'AL EQUIPO'],
    peligrosas: ['NO ESCUCHA A', 'LOS TRABAJADORES'],
    cobrand: { inst: 'azul' },
  },
  {
    type: 'nom-factor',
    title: ['FACTOR 5: RELACIONES', 'LABORALES', 'NEGATIVAS.'],
    body: [
      'Relaciones negativas que',
      'imposibilitan la interacción',
      'con los compañeros para',
      'la solución de problemas y',
      'llevan a un nulo o deficiente',
      'trabajo en equipo y apoyo',
      'social.',
    ],
    cobrand: { inst: 'azul' },
  },
  {
    type: 'nom-ask',
    title: ['AMBIENTE', 'CONFLICTIVO', 'O TENSO'],
    cobrand: { inst: 'azul' },
  },
  {
    type: 'nom-quad-cond',
    inseguras: ['DISCUSIONES', 'CONSTANTES'],
    insalubres: ['FALTA DE APOYO', 'ENTRE COMPAÑEROS'],
    peligrosas: ['AMBIENTE', 'DE TRABAJO', 'HOSTIL'],
    cobrand: { inst: 'azul' },
  },
  {
    type: 'nom-factor',
    shape: 'nom8-yellow-band',
    big: true,
    title: ['FACTOR 6: VIOLENCIA', 'LABORAL.'],
    body: [
      'Actos de hostigamiento:',
      'acoso o malos tratos.',
      'Insultos, humillaciones, marginación',
      'y amenazas que continuamente',
      'dañan la integridad, salud,',
      'estabilidad psicológica o dignidad del',
      'trabajador.',
    ],
    cobrand: { inst: 'azul' },
  },
  {
    type: 'nom-key',
    kicker: ['CARACTERÍSTICAS', 'CLAVE'],
    note: ['No son hechos', 'aislados;', 'ocurre de manera', 'constante.'],
    title: ['ACCIONES', 'SISTEMÁTICAS'],
    cobrand: { inst: 'azul' },
  },
  {
    type: 'nom-key',
    kicker: ['CARACTERÍSTICAS', 'CLAVE'],
    note: ['Acoso psicológico,', 'hostigamiento,', 'malos tratos, burlas,', 'ridiculizaciones', 'y descrédito', 'profesional.'],
    title: ['TIPOS DE', 'ACTOS'],
    cobrand: { inst: 'azul' },
  },
  {
    type: 'nom-key',
    kicker: ['CARACTERÍSTICAS', 'CLAVE'],
    note: ['Afecta la salud', 'física o mental,', 'provocando estrés,', 'depresión, ansiedad', 'o aislamiento.'],
    title: ['DAÑO'],
    cobrand: { inst: 'azul' },
  },
  {
    type: 'nom-ask',
    title: ['¿CÓMO SE VE', 'ESTE FACTOR', 'EN EL TRABAJO', 'DIARIO?'],
    cobrand: { inst: 'azul' },
  },
  {
    type: 'nom-bands',
    a: { h: ['IGNORAR', 'LA PRESENCIA'], s: ['del trabajador o excluirlo', 'de reuniones.'] },
    b: { h: ['COMPARACIONES'], s: ['destructivas, difamaciones o calumnias.'] },
    cobrand: { inst: 'azul' },
  },
  {
    type: 'nom-bands',
    a: { h: ['MANIPULAR'], s: ['situaciones de trabajo para', 'perjudicar el rendimiento', 'del empleado.'] },
    b: { h: ['BLOQUEAR'], s: ['Oportunidades de ascenso', 'o mejora profesional.'] },
    cobrand: { inst: 'azul' },
  },
  {
    type: 'nom-question',
    section: 'Impacto y detección',
    title: ['¿POR QUÉ', 'LA STPS CREÓ', 'LA NOM-035?'],
    cobrand: { inst: 'azul' },
  },
  {
    type: 'nom-worker',
    text: [
      'La NOM-035 se creó',
      'para proteger a todos',
      'los trabajadores de',
      'condiciones',
      'psicosociales que les',
      'puedan generar',
      'desgaste, estrés e',
      'impacto negativo en',
      'salud mental.',
    ],
    cobrand: { inst: 'blanco' },
  },
  {
    type: 'nom-list',
    title: ['AFECTACIONES POR', 'CONDICIONES', 'LABORALES', 'DESFAVORABLES'],
    items: [
      'La salud de los trabajadores.',
      'La seguridad en el trabajo.',
      'El entorno laboral.',
    ],
    cobrand: { inst: 'azul' },
  },
  {
    type: 'nom-question',
    dense: true,
    title: ['DETECTAR FACTORES', 'DE RIESGO PSICOSOCIALES', 'ES EL PRIMER PASO PARA', 'MEJORAR.'],
    cobrand: { inst: 'azul' },
  },
  {
    type: 'expediente',
  },
  {
    type: 'auditoria',
  },
  {
    type: 'nom-resp',
    section: 'Obligaciones',
    kicker: ['RESPONSABILIDAD', 'COMPARTIDA'],
    title: ['¿QUÉ OBLIGACIONES', 'LES CORRESPONDEN?'],
    cobrand: { inst: 'azul' },
  },
  {
    type: 'nom-aqua-title',
    title: ['OBLIGACIONES', 'DEL PATRÓN'],
    cobrand: { inst: 'azul' },
  },
  {
    type: 'nom-oblist',
    title: 'PATRÓN.',
    items: [
      'Establecer y difundir política de prevención de riesgos psicosociales.',
      'Identificar factores de riesgos psicosocial.',
      'Evaluar el entorno organizacional.',
      'Implementar medidas de prevención.',
      'Establecer medidas para controlar factores de riesgo psicosocial.',
      'Identificar eventos traumáticos severos.',
      'Realizar evaluaciones médicas y psicológicas.',
      'Difundir información sobre la NOM-035.',
      'Proporcionar capacitación.',
    ],
    cobrand: { inst: 'azul' },
  },
  {
    type: 'nom-aqua-title',
    title: ['OBLIGACIONES', 'DEL TRABAJADOR'],
    cobrand: { inst: 'azul' },
  },
  {
    type: 'nom-oblist',
    title: 'TRABAJADORES.',
    items: [
      'Seguir las medidas de prevención.',
      'Respetar a compañeros y evitar conflictos.',
      'Abstenerse de realizar actos de violencia laboral.',
      'Participar en evaluaciones relacionadas con la NOM-035.',
      'Informar riesgos y actos contra el entorno laboral saludable.',
      'Denunciar actos de violencia laboral.',
      'Informar eventos traumáticos.',
      'Asistir a capacitaciones.',
      'Participar activamente en cualquier evento relacionado a la NOM-035.',
    ],
    cobrand: { inst: 'azul' },
  },
  {
    type: 'nom-gracias',
    section: 'Cierre',
    title: 'GRACIAS',
    sub: ['Recuerda formar parte del', 'cumplimiento de la NOM-035'],
    cobrand: { inst: 'azul' },
  },
];
